//! Output validation for generated JS and CSS.
//!
//! This module provides syntax validation for the JavaScript and CSS output
//! generated by the Spacetime compiler. By validating at compile time, we can
//! catch syntax errors early before they reach the browser.
//!
//! ## Features
//!
//! - **JavaScript validation**: Uses V8 engine to parse and validate ES6+ syntax
//! - **CSS validation**: Uses lightningcss to parse and validate CSS
//!
//! ## Usage
//!
//! ```rust,ignore
//! use spacetime::validation::{validate_js, validate_css};
//!
//! // Validate JavaScript
//! if let Err(errors) = validate_js("const x = ;") {
//!     for err in errors {
//!         eprintln!("{}", err);
//!     }
//! }
//!
//! // Validate CSS
//! if let Err(errors) = validate_css(".foo { color: }") {
//!     for err in errors {
//!         eprintln!("{}", err);
//!     }
//! }
//! ```

#[cfg(feature = "headless")]
pub mod js;

#[cfg(feature = "headless")]
pub mod css;

// GH-12 / PLAN-137 W6: `%scope element(<tag>)` constraint enforcement. Not
// headless-gated — it runs on every compile path (check, build, serve).
pub mod element_scope;

#[cfg(feature = "headless")]
pub use js::{JsSyntaxError, validate_js};

#[cfg(feature = "headless")]
pub use css::{CssSyntaxError, validate_css};
