//! Generate Tree-sitter grammar.js from %form patterns

use crate::form_extractor::FormPattern;
use std::collections::HashSet;

/// Generate complete grammar.js content
/// This generates a simplified grammar that's compatible with tree-sitter
pub fn generate_grammar(forms: &[FormPattern]) -> String {
    let mut output = String::new();

    // Collect directive names for documentation
    let mut at_directives: HashSet<String> = HashSet::new();
    let mut meta_directives: HashSet<String> = HashSet::new();

    for form in forms {
        match form.prefix {
            '@' => { at_directives.insert(form.directive.clone()); }
            '%' => { meta_directives.insert(form.directive.clone()); }
            _ => {}
        }
    }

    // Header with documentation
    output.push_str(r#"/// <reference types="tree-sitter-cli/dsl" />
// @ts-check
// Generated by treesitter-gen from %form declarations
//
"#);

    // Document known directives
    output.push_str("// Known @ directives:\n");
    let mut sorted_at: Vec<_> = at_directives.iter().collect();
    sorted_at.sort();
    for d in sorted_at {
        output.push_str(&format!("//   @{}\n", d));
    }

    output.push_str("//\n// Known % directives:\n");
    let mut sorted_meta: Vec<_> = meta_directives.iter().collect();
    sorted_meta.sort();
    for d in sorted_meta {
        output.push_str(&format!("//   %{}\n", d));
    }
    output.push_str("//\n\n");

    // Generate the grammar
    output.push_str(&generate_core_grammar());

    output
}

/// Generate the core grammar - a simplified, working grammar
fn generate_core_grammar() -> String {
    r#"module.exports = grammar({
  name: 'spacetime',

  externals: $ => [
    $.emit_content,
  ],

  extras: $ => [
    /\s/,
    $.line_comment,
    $.block_comment,
  ],

  conflicts: $ => [
    [$.directive],
  ],

  word: $ => $.identifier,

  rules: {
    source_file: $ => repeat($._item),

    _item: $ => choice(
      $.directive,
      $.emit_directive,
      $.meta_directive,
      $.scope_block,
    ),

    // @directive patterns
    directive: $ => seq(
      '@',
      $.identifier,
      optional($._directive_args),
      optional($.block),
      optional(';')
    ),

    _directive_args: $ => prec.left(choice(
      seq('(', optional($._args_inner), ')'),
      $._inline_directive_args
    )),

    _inline_directive_args: $ => prec.left(seq(
      repeat1($._inline_arg),
      optional(seq(':', $._property_value))
    )),

    _args_inner: $ => seq(
      $._arg,
      repeat(seq(',', $._arg)),
      optional(',')
    ),

    _arg: $ => choice(
      seq($.variable_ref, ':', $.identifier, optional(seq('=', $._value))),
      seq($.identifier, ':', $._value),
      $._value
    ),

    _inline_arg: $ => choice(
      $.string,
      $.template_string,
      $.duration,
      $.number,
      $.variable_ref,
      $.element_ref,
      $.preset_ref,
      $.identifier
    ),

    // %emit js/css/glsl { raw content }
    emit_directive: $ => seq(
      '%',
      'emit',
      $.identifier,
      '{',
      optional($.emit_content),
      '}'
    ),

    // %meta patterns
    meta_directive: $ => seq(
      '%',
      $.identifier,
      optional($._meta_inline_args),
      optional($.meta_block)
    ),

    _meta_inline_args: $ => choice(
      seq('(', optional($._args_inner), ')'),
      repeat1($._meta_inline_arg)
    ),

    _meta_inline_arg: $ => choice(
      $.variable_ref,
      $.identifier,
      'in',
    ),

    meta_block: $ => seq(
      '{',
      repeat($._meta_item),
      '}'
    ),

    _meta_item: $ => choice(
      $.directive,
      $.meta_directive,
      $.property_decl,
    ),

    // Scope blocks: .selector { ... }
    scope_block: $ => seq(
      $.selector_list,
      $.block
    ),

    selector_list: $ => seq($.selector, repeat(seq(',', $.selector))),

    block: $ => seq('{', repeat($._block_item), '}'),

    _block_item: $ => choice(
      $.directive,
      $.property_decl,
      $.value_decl,
      $.nested_scope,
    ),

    nested_scope: $ => seq(choice($.selector, $.element_ref), $.block),

    property_decl: $ => prec.left(seq(
      $.property_name,
      ':',
      $._property_value,
      optional(';')
    )),

    _property_value: $ => prec.left(repeat1(choice(
      $.transition_arrow,
      $._value,
    ))),

    transition_arrow: $ => seq($._value, '->', $._value),

    value_decl: $ => seq($.variable_ref, ':', $._value, ';'),

    // Values
    _value: $ => choice(
      $.function_call,
      $.color,
      $.duration,
      $.percentage,
      $.number,
      $.string,
      $.template_string,
      $.variable_ref,
      $.element_ref,
      $.preset_ref,
      $.identifier
    ),

    function_call: $ => seq($.identifier, '(', optional($._args_inner), ')'),

    // Comments
    line_comment: $ => seq('//', /.*/),
    block_comment: $ => seq('/*', /[^*]*\*+([^/*][^*]*\*+)*/, '/'),

    // Terminals
    identifier: $ => /[a-zA-Z_][a-zA-Z0-9_-]*/,
    property_name: $ => /[a-zA-Z-][a-zA-Z0-9-]*/,

    variable_ref: $ => seq('$', $.identifier),
    element_ref: $ => seq('&', $.identifier),
    preset_ref: $ => seq('~', $.identifier),

    selector: $ => /[.#\[][^\s{};,]*/,

    string: $ => /"[^"]*"/,
    template_string: $ => /`[^`]*`/,
    number: $ => /-?\d+(\.\d+)?/,
    duration: $ => /-?\d+(\.\d+)?(px|em|rem|vh|vw|%|deg|rad|ms|s)/,
    percentage: $ => /\d+%/,
    color: $ => /#[0-9a-fA-F]{3,8}/,
  },
});
"#.to_string()
}
