//! Generate Tree-sitter highlight queries with sensible defaults

use crate::form_extractor::FormPattern;

/// Generate highlights.scm content
pub fn generate_highlights(_forms: &[FormPattern]) -> String {
    // We use hardcoded sensible defaults rather than deriving from forms
    // The forms inform the grammar structure, highlights are pattern-based

    r#"; Spacetime syntax highlighting
; Generated by treesitter-gen with sensible defaults

; === Comments ===
(line_comment) @comment
(block_comment) @comment

; === Keywords (@directives) ===
(import_statement "@import" @keyword)
(preset_definition "@preset" @keyword)
(pattern_definition "@pattern" @keyword)
(fn_definition "@fn" @keyword)
(directive "@" @keyword)
(directive name: (identifier) @keyword)
(on_block "@on" @keyword)
(pattern_call "@" @keyword)

; === Metasystem keywords (%directives) ===
(primitive_definition "%primitive" @keyword.directive)
(macro_definition "%macro" @keyword.directive)
(emit_block "%emit" @keyword.directive)
(cleanup_block "%cleanup" @keyword.directive)
(inline_cleanup "%cleanup" @keyword.directive)
(exports_block "%exports" @keyword.directive)
(if_block "%if" @keyword.directive)
(else_block "%else" @keyword.directive)
(creates_clause "%creates" @keyword.directive)
(form_clause "%form" @keyword.directive)
(binds_clause "%binds" @keyword.directive)
(derives_clause "%derives" @keyword.directive)
(states_clause "%states" @keyword.directive)
(when_clause "%when" @keyword.directive)
(on_clause "%on" @keyword.directive)
(for_clause "%for" @keyword.directive)
(if_clause "%if" @keyword.directive)
(elif_clause "%elif" @keyword.directive)
(else_clause "%else" @keyword.directive)
(animates_clause "%animates" @keyword.directive)
(applies_clause "%applies" @keyword.directive)
(includes_clause "%includes" @keyword.directive)
(registers_clause "%registers" @keyword.directive)
(template_clause "%template" @keyword.directive)
(transitions_clause "%transitions" @keyword.directive)
(mutate_clause "%mutate" @keyword.directive)
(trigger_clause "%trigger" @keyword.directive)
(scope_clause "%scope" @keyword.directive)

; === Variables ($name) ===
(variable_ref "$" @punctuation.special)
(variable_ref (identifier) @variable)
(variable_path) @variable
(property_path "$" @punctuation.special)
(property_path (identifier) @variable)

; === Element/Preset refs (&name) ===
(element_ref "&" @punctuation.special)
(element_ref (identifier) @variable.special)

; === Strings ===
(string) @string
(template_string) @string.special

; === Numbers ===
(number) @number
(duration) @number
(percentage) @number
(color) @constant

; === Properties ===
(property_name) @property
(property_declaration (property_name) @property)
(css_declaration (property_name) @property)

; === Types ===
(preset_definition type: (_) @type)
(array_type) @type
(object_type) @type
(fn_type "fn" @type.builtin)
(type_field (identifier) @property)
(export_decl (variable_ref) @variable)

; === Functions ===
(function_call (identifier) @function)
(css_function_name) @function.builtin
(easing_function) @function
(calc_expr "calc" @function.builtin)

; === Operators ===
"->" @operator
"<-" @operator
"=>" @operator
"|" @operator
"||" @operator
"&&" @operator
"!" @operator
"==" @operator
"!=" @operator
"<=" @operator
">=" @operator
"<" @operator
">" @operator
":" @punctuation.delimiter
";" @punctuation.delimiter
"," @punctuation.delimiter
"(" @punctuation.bracket
")" @punctuation.bracket
"{" @punctuation.bracket
"}" @punctuation.bracket
"[" @punctuation.bracket
"]" @punctuation.bracket

; === Selectors ===
(selector) @type
(nested_selector) @type
(selector_list (selector) @type)

; === Event names ===
(event_name) @constant

; === Scope names ===
(scope_name) @constant

; === Emit language ===
(emit_block lang: (_) @label)

; === Definition names ===
(primitive_definition name: (identifier) @function.definition)
(macro_definition name: (identifier) @function.definition)
(pattern_definition name: (identifier) @function.definition)
(fn_definition name: (identifier) @function.definition)
(preset_definition name: (element_ref) @variable.definition)

; === Parameters ===
(parameter (element_ref) @variable.parameter)
(parameter (variable_ref) @variable.parameter)
(fn_parameter (identifier) @variable.parameter)

; === Keywords in context ===
"in" @keyword
"as" @keyword
"with" @keyword
"when" @keyword
"on" @keyword

; === Boolean-like ===
"true" @constant.builtin
"false" @constant.builtin
"none" @constant.builtin
"null" @constant.builtin
"#.to_string()
}

/// Generate injections.scm for embedded languages
pub fn generate_injections() -> String {
    r#"; Language injections for embedded code
; Generated by treesitter-gen

; JavaScript in %emit js { ... }
((emit_block
  lang: (identifier) @_lang
  (emit_content) @injection.content)
 (#eq? @_lang "js")
 (#set! injection.language "javascript"))

; CSS in %emit css { ... }
((emit_block
  lang: (identifier) @_lang
  (emit_content) @injection.content)
 (#eq? @_lang "css")
 (#set! injection.language "css"))

; GLSL in %emit glsl { ... }
((emit_block
  lang: (identifier) @_lang
  (emit_content) @injection.content)
 (#eq? @_lang "glsl")
 (#set! injection.language "glsl"))
"#.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generates_highlights() {
        let highlights = generate_highlights(&[]);
        assert!(highlights.contains("@keyword"));
        assert!(highlights.contains("@variable"));
        assert!(highlights.contains("@string"));
        assert!(highlights.contains("@number"));
        assert!(highlights.contains("@comment"));
    }

    #[test]
    fn test_generates_injections() {
        let injections = generate_injections();
        assert!(injections.contains("javascript"));
        assert!(injections.contains("css"));
        assert!(injections.contains("glsl"));
    }
}
