//! Debug Runtime Generation
//!
//! Generates the JavaScript runtime instrumentation that creates the
//! `window.__ST_DEBUG__` object for tracking timelines, signals, and state machines.

use super::DebuggerConfig;

/// Generate the debug runtime JavaScript code
///
/// This creates the `window.__ST_DEBUG__` object with methods for:
/// - Registering and tracking timeline progress
/// - Monitoring signal values with change detection
/// - Tracking state machine states and transitions
/// - Recording history of all changes
///
/// # Arguments
///
/// * `config` - The debugger configuration
///
/// # Returns
///
/// A JavaScript string containing the debug runtime code
pub fn generate_debug_runtime(config: &DebuggerConfig) -> String {
    let max_history = config.max_history_entries;
    let record_history = config.record_history;

    format!(
        r#"// Spacetime Debug Runtime
// Generated by spacetime debugger
(function() {{
  'use strict';

  // Debug runtime object
  window.__ST_DEBUG__ = {{
    // Version
    version: '1.0.0',

    // Configuration
    config: {{
      recordHistory: {record_history},
      maxHistoryEntries: {max_history},
    }},

    // Timeline tracking
    timelines: new Map(),

    // Signal tracking
    signals: new Map(),

    // State machine tracking
    states: new Map(),

    // Error tracking
    errors: [],

    // Change history
    history: [],

    // Panel reference (set when panel is mounted)
    panel: null,

    // Listeners for state changes
    listeners: new Set(),

    // =========================================================================
    // Timeline Methods
    // =========================================================================

    /**
     * Register a timeline for tracking
     * @param {{string}} id - Timeline identifier
     * @param {{Object}} config - Timeline configuration
     */
    registerTimeline: function(id, config) {{
      this.timelines.set(id, {{
        id: id,
        type: config.type || 'unknown',
        progress: 0,
        scope: config.scope || null,
        range: config.range || [0, 1],
        createdAt: Date.now(),
      }});

      this._recordHistory('timeline.register', {{ id, config }});
      this._notifyListeners('timeline.register', {{ id }});
    }},

    /**
     * Update timeline progress
     * @param {{string}} id - Timeline identifier
     * @param {{number}} progress - Progress value (0-1)
     */
    updateProgress: function(id, progress) {{
      const timeline = this.timelines.get(id);
      if (timeline) {{
        const oldProgress = timeline.progress;
        timeline.progress = Math.max(0, Math.min(1, progress));
        timeline.lastUpdate = Date.now();

        // Only record if change is significant (> 0.1%)
        if (Math.abs(oldProgress - progress) > 0.001) {{
          this._recordHistory('timeline.progress', {{
            id,
            from: oldProgress,
            to: timeline.progress,
          }});
          this._notifyListeners('timeline.progress', {{ id, progress: timeline.progress }});
        }}
      }}
    }},

    /**
     * Get all timeline states
     * @returns {{Array}} Array of timeline state objects
     */
    getTimelines: function() {{
      return Array.from(this.timelines.values());
    }},

    // =========================================================================
    // Signal Methods
    // =========================================================================

    /**
     * Register or update a signal value
     * @param {{Element|string}} el - Element or element identifier
     * @param {{string}} name - Signal name
     * @param {{*}} value - Signal value
     */
    setSignal: function(el, name, value) {{
      const elId = typeof el === 'string' ? el : this._getElementId(el);
      const key = `${{elId}}:${{name}}`;

      const existing = this.signals.get(key);
      const oldValue = existing ? existing.value : undefined;

      this.signals.set(key, {{
        element: elId,
        name: name,
        value: value,
        previousValue: oldValue,
        changedAt: Date.now(),
        changeCount: existing ? existing.changeCount + 1 : 1,
      }});

      if (oldValue !== value) {{
        this._recordHistory('signal.change', {{
          element: elId,
          name,
          from: oldValue,
          to: value,
        }});
        this._notifyListeners('signal.change', {{ element: elId, name, value }});
      }}
    }},

    /**
     * Get signal value
     * @param {{Element|string}} el - Element or element identifier
     * @param {{string}} name - Signal name
     * @returns {{*}} Signal value or undefined
     */
    getSignal: function(el, name) {{
      const elId = typeof el === 'string' ? el : this._getElementId(el);
      const key = `${{elId}}:${{name}}`;
      const signal = this.signals.get(key);
      return signal ? signal.value : undefined;
    }},

    /**
     * Get all signals
     * @returns {{Array}} Array of signal state objects
     */
    getSignals: function() {{
      return Array.from(this.signals.values());
    }},

    // =========================================================================
    // State Machine Methods
    // =========================================================================

    /**
     * Register a state machine
     * @param {{Element|string}} el - Element or element identifier
     * @param {{string}} initialState - Initial state
     * @param {{Array<string>}} states - Valid states
     */
    registerStateMachine: function(el, initialState, states) {{
      const elId = typeof el === 'string' ? el : this._getElementId(el);

      this.states.set(elId, {{
        element: elId,
        current: initialState,
        previous: null,
        validStates: states || [],
        transitions: [],
        createdAt: Date.now(),
      }});

      this._recordHistory('state.register', {{
        element: elId,
        initial: initialState,
        states,
      }});
      this._notifyListeners('state.register', {{ element: elId, state: initialState }});
    }},

    /**
     * Update state machine state
     * @param {{Element|string}} el - Element or element identifier
     * @param {{string}} from - Previous state
     * @param {{string}} to - New state
     * @param {{string}} event - Event that triggered the transition
     */
    setState: function(el, from, to, event) {{
      const elId = typeof el === 'string' ? el : this._getElementId(el);

      let sm = this.states.get(elId);
      if (!sm) {{
        // Auto-register if not found
        sm = {{
          element: elId,
          current: to,
          previous: from,
          validStates: [],
          transitions: [],
          createdAt: Date.now(),
        }};
        this.states.set(elId, sm);
      }}

      sm.previous = from;
      sm.current = to;
      sm.lastTransition = {{
        from,
        to,
        event: event || 'unknown',
        timestamp: Date.now(),
      }};
      sm.transitions.push(sm.lastTransition);

      // Keep only last 50 transitions per state machine
      if (sm.transitions.length > 50) {{
        sm.transitions = sm.transitions.slice(-50);
      }}

      this._recordHistory('state.transition', {{
        element: elId,
        from,
        to,
        event,
      }});
      this._notifyListeners('state.transition', {{ element: elId, from, to, event }});
    }},

    /**
     * Get all state machines
     * @returns {{Array}} Array of state machine objects
     */
    getStateMachines: function() {{
      return Array.from(this.states.values());
    }},

    // =========================================================================
    // Error Tracking Methods
    // =========================================================================

    /**
     * Record a runtime error
     * @param {{string}} source - What component/source threw the error (e.g., 'data-source')
     * @param {{Error|string}} error - The error object or message
     * @param {{Object}} context - Additional context (name, url, etc.)
     */
    recordError: function(source, error, context) {{
      const entry = {{
        id: Date.now() + '-' + Math.random().toString(36).substr(2, 9),
        source: source,
        message: error.message || String(error),
        stack: error.stack || null,
        context: context || {{}},
        timestamp: Date.now(),
      }};

      this.errors.push(entry);
      this._recordHistory('error', entry);
      this._notifyListeners('error', entry);

      // Also show visual indicator on panel
      if (this.panel && typeof this.panel.onError === 'function') {{
        this.panel.onError(entry);
      }}
    }},

    /**
     * Get all recorded errors
     * @returns {{Array}} Array of error entries
     */
    getErrors: function() {{
      return this.errors.slice();
    }},

    /**
     * Clear all recorded errors
     */
    clearErrors: function() {{
      this.errors = [];
      this._notifyListeners('errors.clear', null);
    }},

    // =========================================================================
    // History Methods
    // =========================================================================

    /**
     * Get change history
     * @param {{number}} limit - Maximum entries to return (default: all)
     * @returns {{Array}} Array of history entries
     */
    getHistory: function(limit) {{
      if (limit && limit > 0) {{
        return this.history.slice(-limit);
      }}
      return this.history.slice();
    }},

    /**
     * Clear history
     */
    clearHistory: function() {{
      this.history = [];
      this._notifyListeners('history.clear', {{}});
    }},

    // =========================================================================
    // Snapshot Methods
    // =========================================================================

    /**
     * Get a complete snapshot of all debug state
     * @returns {{Object}} Snapshot object
     */
    getSnapshot: function() {{
      return {{
        timestamp: Date.now(),
        timelines: this.getTimelines(),
        signals: this.getSignals(),
        stateMachines: this.getStateMachines(),
        historyLength: this.history.length,
      }};
    }},

    /**
     * Export state as JSON string
     * @returns {{string}} JSON string
     */
    exportJSON: function() {{
      return JSON.stringify(this.getSnapshot(), null, 2);
    }},

    // =========================================================================
    // Listener Methods
    // =========================================================================

    /**
     * Add a change listener
     * @param {{function}} callback - Listener callback
     * @returns {{function}} Unsubscribe function
     */
    subscribe: function(callback) {{
      this.listeners.add(callback);
      return () => this.listeners.delete(callback);
    }},

    // =========================================================================
    // Internal Methods
    // =========================================================================

    /**
     * Record an entry in history
     * @private
     */
    _recordHistory: function(type, data) {{
      if (!this.config.recordHistory) return;

      const entry = {{
        type,
        data,
        timestamp: Date.now(),
      }};

      this.history.push(entry);

      // Trim history if over limit
      if (this.config.maxHistoryEntries > 0 &&
          this.history.length > this.config.maxHistoryEntries) {{
        this.history = this.history.slice(-this.config.maxHistoryEntries);
      }}
    }},

    /**
     * Notify all listeners of a change
     * @private
     */
    _notifyListeners: function(type, data) {{
      this.listeners.forEach(listener => {{
        try {{
          listener(type, data);
        }} catch (e) {{
          console.error('[ST_DEBUG] Listener error:', e);
        }}
      }});

      // Also notify panel if mounted
      if (this.panel && typeof this.panel.onDebugEvent === 'function') {{
        try {{
          this.panel.onDebugEvent(type, data);
        }} catch (e) {{
          console.error('[ST_DEBUG] Panel notification error:', e);
        }}
      }}
    }},

    /**
     * Get a stable identifier for an element
     * @private
     */
    _getElementId: function(el) {{
      if (!el) return 'unknown';
      if (el.id) return '#' + el.id;
      if (el.dataset && el.dataset.stId) return '[data-st-id="' + el.dataset.stId + '"]';
      // Handle both HTML elements (className is string) and SVG elements (className is SVGAnimatedString)
      const classNameStr = typeof el.className === 'string' ? el.className : (el.className && el.className.baseVal);
      if (classNameStr) {{
        const classes = classNameStr.split(' ').filter(c => c).slice(0, 2).join('.');
        if (classes) return el.tagName.toLowerCase() + '.' + classes;
      }}
      return el.tagName ? el.tagName.toLowerCase() : 'unknown';
    }},
  }};

  // Print friendly welcome message
  console.log(
    '%c╭─────────────────────────────────────────────────────────╮\n' +
    '│  ✨ Spacetime Debug Mode Active                         │\n' +
    '├─────────────────────────────────────────────────────────┤\n' +
    '│  Available Commands:                                    │\n' +
    '│                                                         │\n' +
    '│  __ST_DEBUG__.getTimelines()     List all timelines     │\n' +
    '│  __ST_DEBUG__.getSignals()       List all signals       │\n' +
    '│  __ST_DEBUG__.getStateMachines() List state machines    │\n' +
    '│  __ST_DEBUG__.getErrors()        List runtime errors    │\n' +
    '│  __ST_DEBUG__.clearErrors()      Clear error list       │\n' +
    '│  __ST_DEBUG__.getSnapshot()      Full state snapshot    │\n' +
    '│  __ST_DEBUG__.exportJSON()       Export as JSON         │\n' +
    '│  __ST_DEBUG__.getHistory(n)      Last n history events  │\n' +
    '│  __ST_DEBUG__.clearHistory()     Clear event history    │\n' +
    '│                                                         │\n' +
    '│  Tip: Click the panel header to expand/collapse         │\n' +
    '│       Use ⋮ menu for quick commands                     │\n' +
    '╰─────────────────────────────────────────────────────────╯',
    'color: #6366f1; font-family: monospace;'
  );

  // =========================================================================
  // Global Error Handlers (only active in debug mode)
  // =========================================================================

  // Catch uncaught errors
  window.addEventListener('error', function(event) {{
    window.__ST_DEBUG__.recordError('uncaught', event.error || new Error(event.message), {{
      filename: event.filename,
      lineno: event.lineno,
      colno: event.colno
    }});
  }});

  // Catch unhandled promise rejections
  window.addEventListener('unhandledrejection', function(event) {{
    const error = event.reason instanceof Error
      ? event.reason
      : new Error(String(event.reason));
    window.__ST_DEBUG__.recordError('unhandled-promise', error, {{}});
  }});

}})();
"#,
        record_history = if record_history { "true" } else { "false" },
        max_history = max_history
    )
}

/// Debug instrumentation hooks loaded from public/debugger/hooks.js
const DEBUG_HOOKS: &str = include_str!("../../public/debugger/hooks.js");

/// Generate minimal instrumentation hooks to inject into the main runtime
///
/// These hooks call into `__ST_DEBUG__` when present, allowing the debug
/// runtime to track state changes without modifying the core runtime behavior.
/// Events are buffered if `__ST_DEBUG__` isn't ready yet, then replayed.
pub fn generate_debug_hooks() -> String {
    DEBUG_HOOKS.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_debug_runtime_defaults() {
        let config = DebuggerConfig::default();
        let js = generate_debug_runtime(&config);

        // Check that the runtime is generated
        assert!(js.contains("window.__ST_DEBUG__"));
        assert!(js.contains("timelines: new Map()"));
        assert!(js.contains("signals: new Map()"));
        assert!(js.contains("states: new Map()"));
        assert!(js.contains("errors: []"));
        assert!(js.contains("history: []"));

        // Check methods exist
        assert!(js.contains("registerTimeline:"));
        assert!(js.contains("updateProgress:"));
        assert!(js.contains("setSignal:"));
        assert!(js.contains("setState:"));
        assert!(js.contains("recordError:"));
        assert!(js.contains("getErrors:"));
        assert!(js.contains("clearErrors:"));
        assert!(js.contains("getSnapshot:"));
    }

    #[test]
    fn test_generate_debug_runtime_custom_config() {
        let config = DebuggerConfig::new().record_history(false).max_history(500);
        let js = generate_debug_runtime(&config);

        assert!(js.contains("recordHistory: false"));
        assert!(js.contains("maxHistoryEntries: 500"));
    }

    #[test]
    fn test_generate_debug_hooks() {
        let hooks = generate_debug_hooks();

        assert!(hooks.contains("__stDebugHook"));
        assert!(hooks.contains("timeline:"));
        assert!(hooks.contains("signal:"));
        assert!(hooks.contains("state:"));
        assert!(hooks.contains("registerTimeline:"));
        assert!(hooks.contains("registerStateMachine:"));
    }
}
