//! HTML Emitter
//!
//! Converts HtmlExpr IR types to HTML strings.
//!
//! This is primarily a stub for future template generation features.
//! Currently, most HTML comes from the input HTML files rather than
//! being generated by the compiler.

use crate::ir::{AttrPart, HtmlExpr, JsExpr};

use super::EmitOptions;

/// Emit an HTML expression
pub fn emit(expr: &HtmlExpr, opts: &EmitOptions) -> String {
    match expr {
        HtmlExpr::Element {
            tag,
            attrs,
            children,
            ..
        } => emit_element(tag, attrs, children, opts),
        HtmlExpr::Text(text) => escape_html_text(text),
        HtmlExpr::Hole(expr) => emit_hole(expr),
        HtmlExpr::Raw(s) => s.clone(),
        HtmlExpr::Html(s) => super::html_reactive::component_html_to_exprs(s)
            .iter()
            .map(|expr| emit(expr, opts))
            .collect(),
        // Reactive markdown has no static rendering: snarkdown runs in the
        // browser, so the SSG pass emits an empty display:contents span that
        // the reactive builder fills on mount (parity with a reactive text
        // hole rendering empty statically).
        HtmlExpr::Markdown(_) => String::from("<span style=\"display:contents\"></span>"),
    }
}

/// Emit a text-position hole. In the static W1 slice a hole has no element context to
/// resolve a signal against, so it is rendered as a placeholder comment carrying the raw
/// expression source. The reactive emit phase (PLAN-023 W3/W4) replaces this with a real
/// hydrated value once an `EmitContext` is available.
/// Emit a text-position hole. NOTE (FEAT-078): file-scope HTML reactivity moved to
/// `emit::html_hydrate` (static initial value + a `data-st-hole` marker + Global-scope
/// hydration JS). This generic `emit::html` path is used only for hole-FREE fragments
/// (`FragmentKind::Html`, never constructed today). A hole reaching here is unexpected; emit
/// nothing rather than a stale `<!--st-hole-->` comment (the obsolete W1 placeholder).
fn emit_hole(_expr: &JsExpr) -> String {
    String::new()
}

/// Emit a single attribute value from its part list.
/// Emit a single attribute value from its part list. Holes are handled by `emit::html_hydrate`
/// (FEAT-078); here (hole-free fragment path) a hole contributes nothing rather than a stale
/// `{st-hole:…}` placeholder.
fn emit_attr_parts(parts: &[AttrPart]) -> String {
    let mut out = String::new();
    for part in parts {
        match part {
            AttrPart::Lit(s) => out.push_str(&escape_attr_value(s)),
            AttrPart::Hole(_) => {}
        }
    }
    out
}

/// Emit multiple HTML expressions
pub fn emit_all(exprs: &[HtmlExpr], opts: &EmitOptions) -> String {
    exprs
        .iter()
        .map(|e| emit(e, opts))
        .collect::<Vec<_>>()
        .join(if opts.minify { "" } else { "\n" })
}

/// Emit an HTML element
fn emit_element(
    tag: &str,
    attrs: &[(String, Vec<AttrPart>)],
    children: &[HtmlExpr],
    opts: &EmitOptions,
) -> String {
    let attrs_str = if attrs.is_empty() {
        String::new()
    } else {
        let attr_parts: Vec<_> = attrs
            .iter()
            .map(|(k, parts)| {
                let is_boolean = parts.is_empty()
                    || (parts.len() == 1 && matches!(&parts[0], AttrPart::Lit(s) if s.is_empty()));
                if is_boolean {
                    // Boolean attribute
                    k.clone()
                } else {
                    format!("{}=\"{}\"", k, emit_attr_parts(parts))
                }
            })
            .collect();
        format!(" {}", attr_parts.join(" "))
    };

    // Self-closing tags (void elements)
    if is_void_element(tag) {
        return format!("<{}{}>", tag, attrs_str);
    }

    // Empty elements
    if children.is_empty() {
        return format!("<{}{}></{}>", tag, attrs_str, tag);
    }

    // Elements with children
    let children_str = if opts.minify {
        children
            .iter()
            .map(|c| emit(c, opts))
            .collect::<Vec<_>>()
            .join("")
    } else {
        let indent = &opts.indent;
        let nl = &opts.newline;
        let child_strs: Vec<_> = children
            .iter()
            .map(|c| format!("{}{}", indent, emit(c, opts)))
            .collect();
        format!("{}{}{}", nl, child_strs.join(nl), nl)
    };

    format!("<{}{}>{}</{}>", tag, attrs_str, children_str, tag)
}

/// Check if a tag is a void element (self-closing)
fn is_void_element(tag: &str) -> bool {
    matches!(
        tag.to_lowercase().as_str(),
        "area"
            | "base"
            | "br"
            | "col"
            | "embed"
            | "hr"
            | "img"
            | "input"
            | "link"
            | "meta"
            | "param"
            | "source"
            | "track"
            | "wbr"
    )
}

/// Escape text content for HTML
fn escape_html_text(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for c in text.chars() {
        match c {
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '&' => out.push_str("&amp;"),
            c => out.push(c),
        }
    }
    out
}

/// Escape attribute values for HTML
fn escape_attr_value(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for c in value.chars() {
        match c {
            '"' => out.push_str("&quot;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '&' => out.push_str("&amp;"),
            c => out.push(c),
        }
    }
    out
}
